// Package setup generates the SQL an operator runs to provision pglockr's
// database role, and the remediation shown when the connected role is missing
// privileges. pglockr never applies these itself — the operator reviews and
// runs them against their cluster.
package setup

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"strings"
)

// GrantOptions parameterises the generated provisioning script.
type GrantOptions struct {
	Role     string // role name to create (e.g. pglockr_ro)
	Password string // login password; if empty the caller should generate one
	Signal   bool   // include pg_signal_backend (cancel/terminate)
}

// Script returns a complete, reviewable SQL script that creates the role and
// grants it the privileges pglockr needs.
func Script(o GrantOptions) string {
	role := quoteIdent(o.Role)
	var b strings.Builder
	fmt.Fprintf(&b, "-- pglockr access role, generated by `pglockr grants`. Review before applying.\n")
	fmt.Fprintf(&b, "-- pg_monitor lets pglockr read other backends' query texts;\n")
	fmt.Fprintf(&b, "-- pg_signal_backend lets it cancel/terminate them.\n\n")
	fmt.Fprintf(&b, "CREATE ROLE %s LOGIN PASSWORD %s;\n", role, quoteLiteral(o.Password))
	fmt.Fprintf(&b, "GRANT pg_monitor TO %s;\n", role)
	if o.Signal {
		fmt.Fprintf(&b, "GRANT pg_signal_backend TO %s;\n", role)
	} else {
		fmt.Fprintf(&b, "-- (read-only viewer: pg_signal_backend omitted; cancel/terminate disabled)\n")
	}
	return b.String()
}

// Remediation returns just the GRANT statements needed to fix an existing role
// that is missing privileges — used by the startup preflight message.
func Remediation(role string, needStats, needSignal bool) string {
	r := quoteIdent(role)
	var lines []string
	if needStats {
		lines = append(lines, fmt.Sprintf("GRANT pg_monitor TO %s;", r))
	}
	if needSignal {
		lines = append(lines, fmt.Sprintf("GRANT pg_signal_backend TO %s;", r))
	}
	return strings.Join(lines, "\n")
}

// RandomPassword returns a URL-safe random password with no characters that
// need escaping in a SQL string literal.
func RandomPassword() (string, error) {
	buf := make([]byte, 18) // 144 bits
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// quoteIdent double-quotes a SQL identifier, escaping embedded quotes.
func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

// quoteLiteral single-quotes a SQL string literal, escaping embedded quotes.
func quoteLiteral(s string) string {
	return `'` + strings.ReplaceAll(s, `'`, `''`) + `'`
}
